namespace Gateway.Contracts;

public static class ErrorCodes
{
    public const string VALIDATION_FAILED = "VALIDATION_FAILED";
    public const string AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    public const string CALLER_NOT_AUTHORIZED = "CALLER_NOT_AUTHORIZED";
    public const string AGENT_IDENTITY_MISMATCH = "AGENT_IDENTITY_MISMATCH";
    public const string AGENT_DISABLED = "AGENT_DISABLED";
    public const string AGENT_NOT_FOUND = "AGENT_NOT_FOUND";
    public const string OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND";
    public const string DUPLICATE_EXTERNAL_AGENT_ID = "DUPLICATE_EXTERNAL_AGENT_ID";
    public const string IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT";
    public const string CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT";
    public const string INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION";
    public const string PROVISIONING_FAILED = "PROVISIONING_FAILED";
    public const string UNSUPPORTED_FEATURE_CONFIGURATION = "UNSUPPORTED_FEATURE_CONFIGURATION";
    public const string PURVIEW_POLICY_BLOCKED = "PURVIEW_POLICY_BLOCKED";
    public const string PURVIEW_DEPENDENCY_UNAVAILABLE = "PURVIEW_DEPENDENCY_UNAVAILABLE";
    public const string AGENT365_DEPENDENCY_UNAVAILABLE = "AGENT365_DEPENDENCY_UNAVAILABLE";
    public const string RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
    public const string PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE";
    public const string SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
}
