namespace Gateway.Contracts;

public static class ErrorCodes
{
    public const string VALIDATION_FAILED = "VALIDATION_FAILED";
    public const string AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    public const string CALLER_NOT_AUTHORIZED = "CALLER_NOT_AUTHORIZED";
    public const string AGENT_IDENTITY_MISMATCH = "AGENT_IDENTITY_MISMATCH";
    public const string AGENT_DISABLED = "AGENT_DISABLED";
    public const string AGENT_NOT_FOUND = "AGENT_NOT_FOUND";
    public const string AGENT_INGRESS_CREDENTIAL_NOT_FOUND = "AGENT_INGRESS_CREDENTIAL_NOT_FOUND";
    public const string AGENT_INGRESS_CREDENTIAL_LAST_USABLE = "AGENT_INGRESS_CREDENTIAL_LAST_USABLE";
    public const string OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND";
    public const string DUPLICATE_EXTERNAL_AGENT_ID = "DUPLICATE_EXTERNAL_AGENT_ID";
    public const string IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT";
    public const string CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT";
    public const string INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION";
    public const string PROVISIONING_FAILED = "PROVISIONING_FAILED";
    public const string PROVISIONING_DISABLED = "PROVISIONING_DISABLED";
    public const string PROVISIONING_INVALID_MESSAGE = "PROVISIONING_INVALID_MESSAGE";
    public const string PROVISIONING_JOB_MISMATCH = "PROVISIONING_JOB_MISMATCH";
    public const string PROVISIONING_LEGACY_JOB = "PROVISIONING_LEGACY_JOB";
    public const string PROVISIONING_STATE_INVALID = "PROVISIONING_STATE_INVALID";
    public const string PROVISIONING_STEP_NOT_IMPLEMENTED = "PROVISIONING_STEP_NOT_IMPLEMENTED";
    public const string PROVISIONING_CONFIGURATION_INVALID = "PROVISIONING_CONFIGURATION_INVALID";
    public const string PROVISIONING_PREVIEW_DISABLED = "PROVISIONING_PREVIEW_DISABLED";
    public const string PROVISIONING_DEPENDENCY_FORBIDDEN = "PROVISIONING_DEPENDENCY_FORBIDDEN";
    public const string PROVISIONING_DEPENDENCY_THROTTLED = "PROVISIONING_DEPENDENCY_THROTTLED";
    public const string PROVISIONING_DEPENDENCY_UNAVAILABLE = "PROVISIONING_DEPENDENCY_UNAVAILABLE";
    public const string PROVISIONING_AMBIGUOUS_RESULT = "PROVISIONING_AMBIGUOUS_RESULT";
    public const string AGENT365_REGISTRY_ACTION_REQUIRED = "AGENT365_REGISTRY_ACTION_REQUIRED";
    public const string AGENT365_REGISTRY_DELEGATED_ACCESS_REQUIRED = "AGENT365_REGISTRY_DELEGATED_ACCESS_REQUIRED";
    public const string AGENT365_REGISTRY_REQUEST_REJECTED = "AGENT365_REGISTRY_REQUEST_REJECTED";
    public const string PROVISIONING_RETRIES_EXHAUSTED = "PROVISIONING_RETRIES_EXHAUSTED";
    public const string AGENT_IDENTITY_BLUEPRINT_CATALOG_UNAVAILABLE = "AGENT_IDENTITY_BLUEPRINT_CATALOG_UNAVAILABLE";
    public const string AGENT_IDENTITY_BLUEPRINT_CATALOG_INVALID_RESPONSE = "AGENT_IDENTITY_BLUEPRINT_CATALOG_INVALID_RESPONSE";
    public const string AGENT_IDENTITY_BLUEPRINT_INCOMPATIBLE = "AGENT_IDENTITY_BLUEPRINT_INCOMPATIBLE";
    public const string AGENT365_PLATFORM_ACCEPTANCE_UNCONFIGURED = "AGENT365_PLATFORM_ACCEPTANCE_UNCONFIGURED";
    public const string UNSUPPORTED_FEATURE_CONFIGURATION = "UNSUPPORTED_FEATURE_CONFIGURATION";
    public const string PURVIEW_POLICY_BLOCKED = "PURVIEW_POLICY_BLOCKED";
    public const string PURVIEW_DEPENDENCY_UNAVAILABLE = "PURVIEW_DEPENDENCY_UNAVAILABLE";
    public const string AGENT365_DEPENDENCY_UNAVAILABLE = "AGENT365_DEPENDENCY_UNAVAILABLE";
    public const string RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
    public const string PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE";
    public const string SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
}
