using System.Diagnostics;
using Gateway.Infrastructure.Persistence;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace Gateway.TestSupport;

public sealed class LocalSqlDatabase : IAsyncDisposable
{
    private readonly LocalSqlInstance _instance;
    private readonly string _directory;
    private bool _ownsDatabase;
    private bool _disposed;

    private LocalSqlDatabase(LocalSqlInstance instance)
    {
        _instance = instance;
        Name = $"m1_test_{Guid.NewGuid():N}";
        ConnectionString = LocalSqlConnectionGuard.CreateConnectionString(instance.Name, Name, instance.PipeName);
        _directory = Path.GetFullPath(Path.Combine("TestResults", "m1-localdb", Name));
    }

    public string Name { get; }
    public string ConnectionString { get; }

    internal static async Task<LocalSqlDatabase> CreateOwnedAsync(LocalSqlInstance instance)
    {
        var database = new LocalSqlDatabase(instance);
        if (Directory.Exists(database._directory))
            throw new IOException("Refusing to reuse an existing SQL test file directory.");
        Directory.CreateDirectory(database._directory);
        try
        {
            await using var connection = new SqlConnection(LocalSqlConnectionGuard.MasterConnectionString(instance.Name, instance.PipeName));
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandTimeout = 60;
            var dataPath = Path.Combine(database._directory, "test.mdf").Replace("'", "''");
            var logPath = Path.Combine(database._directory, "test.ldf").Replace("'", "''");
            command.CommandText = $"""
                CREATE DATABASE [{database.Name}]
                ON PRIMARY (NAME = N'{database.Name}', FILENAME = N'{dataPath}')
                LOG ON (NAME = N'{database.Name}_log', FILENAME = N'{logPath}');
                """;
            await command.ExecuteNonQueryAsync();
            database._ownsDatabase = true;
            await using var context = database.CreateContext();
            await context.Database.EnsureCreatedAsync();
            return database;
        }
        catch
        {
            await database.DisposeAsync();
            throw;
        }
    }

    public GatewayDbContext CreateContext()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        LocalSqlConnectionGuard.Validate(ConnectionString, _instance.Name, Name, _instance.PipeName);
        return new GatewayDbContext(new DbContextOptionsBuilder<GatewayDbContext>()
            .UseSqlServer(ConnectionString, sql => sql.CommandTimeout(40))
            .Options);
    }

    public async Task ExecuteAsync(string sql)
    {
        await using var context = CreateContext();
        await context.Database.ExecuteSqlRawAsync(sql);
    }

    public async Task WaitForApplicationLockWaitAsync()
    {
        await using var context = CreateContext();
        var timer = Stopwatch.StartNew();
        while (timer.Elapsed < TimeSpan.FromSeconds(10))
        {
            var waiting = await context.Database.SqlQueryRaw<int>("""
                SELECT COUNT(*) AS [Value] FROM sys.dm_tran_locks
                WHERE resource_database_id = DB_ID()
                  AND resource_type = 'APPLICATION' AND request_status = 'WAIT'
                """).SingleAsync();
            if (waiting != 0)
                return;
            await Task.Delay(20);
        }
        throw new TimeoutException("The competing SQL request never reached its real application-lock wait.");
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed)
            return;
        if (_ownsDatabase)
        {
            await using var connection = new SqlConnection(LocalSqlConnectionGuard.MasterConnectionString(_instance.Name, _instance.PipeName));
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandTimeout = 60;
            // Both identifiers were generated by this fixture, never read from settings or environment.
            LocalSqlConnectionGuard.ValidateOwnedName(Name);
            command.CommandText = $"""
                ALTER DATABASE [{Name}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
                DROP DATABASE [{Name}];
                SELECT COUNT(*) FROM sys.databases WHERE name = @name;
                """;
            command.Parameters.AddWithValue("@name", Name);
            if (Convert.ToInt32(await command.ExecuteScalarAsync()) != 0)
                throw new InvalidOperationException("The owned SQL test database was not removed.");
            _ownsDatabase = false;
        }
        if (Directory.Exists(_directory))
            Directory.Delete(_directory, recursive: false);
        _disposed = true;
    }
}
