namespace Gateway.Contracts.Dtos;

public sealed record ProtectionAdminOperationStepDto(
    Guid Id,
    int OrderIndex,
    string Step,
    string Status,
    int AttemptCount,
    string RetryDisposition,
    DateTime? NextAttemptAtUtc,
    bool CanRetry,
    bool RequiresManualIntervention,
    Guid? ReadbackReferenceId,
    string? FailureCode,
    DateTime? StartedAtUtc,
    DateTime? CompletedAtUtc);

public sealed record ProtectionAdminOperationDto(
    Guid Id,
    int WorkflowVersion,
    string Type,
    string Status,
    Guid TenantId,
    string ActorObjectId,
    string TargetType,
    string TargetIdentifier,
    string ReviewedPayloadHash,
    Guid IdempotencyKey,
    string ExpectedRowVersion,
    string RetryDisposition,
    int AttemptCount,
    int MaximumAttempts,
    DateTime? NextAttemptAtUtc,
    bool CanRetry,
    bool RequiresManualIntervention,
    Guid CorrelationId,
    Guid? ReadbackReferenceId,
    string? FailureCode,
    string? RequiredAction,
    IReadOnlyList<string> Blockers,
    DateTime CreatedAtUtc,
    DateTime? StartedAtUtc,
    DateTime? CompletedAtUtc,
    DateTime UpdatedAtUtc,
    IReadOnlyList<ProtectionAdminOperationStepDto> Steps,
    string RowVersion);
